name: 'Qoder Core Logic'
description: 'Downloads and runs the qoder-cli with specified prompts.'

inputs:
  prompt:
    description: 'The main prompt string. Mutually exclusive with prompt_file_path.'
    required: false
  prompt_path:
    description: 'The path to the file containing the main prompt. Mutually exclusive with prompt.'
    required: false
  system_prompt:
    description: 'The system prompt string. Mutually exclusive with system_prompt_path.'
    required: false
  system_prompt_path:
    description: 'The path to the file containing the system prompt. Mutually exclusive with system_prompt.'
    required: false
  dashscope_api_key:
    description: 'The API key for the Dashscope service.'
    required: true
  config:
    description: 'An optional JSON string to configure qoder-cli. This will be written to .qoder-cli.json.'
    required: false
  oidc_token:
    description: 'The OIDC token for authentication.'
    required: false



runs:
  using: 'node20'
  main: 'dist/index.js'