name: 'Qoder Core Action'
description: 'Downloads and runs the qoder-cli with specified prompts.'

inputs:
  prompt:
    description: 'The main prompt string. Mutually exclusive with prompt_file_path.'
    required: false
  prompt_path:
    description: 'The path to the file containing the main prompt. Mutually exclusive with prompt.'
    required: false
  qoder_user_info:
    description: 'User information for Qoder authentication.'
    required: true
  qoder_machine_id:
    description: 'Machine ID for Qoder authentication.'
    required: true
  config:
    description: 'An optional JSON string to configure qoder-cli. This will be written to .qoder-cli.json.'
    required: false


runs:
  using: 'node20'
  main: 'dist/index.js'